### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by medihack** [peggyjs/code-peggy-language#20]
Would it be possible to publish the extension also to [Open VSX](https://open-vsx.org/)? That way it can also be used with [Gitpod](https://www.gitpod.io/) and [Theia](https://theia-ide.org/). This would be really great :-)

**Comment by hildjj** [comment]
Published: https://open-vsx.org/extension/PeggyJS/peggy-language

I am leaving this ticket open until I get verified, via https://github.com/EclipseFdn/open-vsx.org/issues/686

**Comment by medihack** [comment]
Thanks for publishing it there. Unfortunately, I am not able to install it in Gitpod (`Can't install 'peggyjs.peggy-language' extension because it is not compatible with the current version of VS Code (version 1.59.0).`), but I have no problem with installing a downloaded vsix file of Peggy (`PeggyJS.peggy-language-2.2.0.vsix`). So maybe there is some unneeded version constraint (not sure about that).

**Comment by medihack** [comment]
I am not sure how often they update. We could leave the issue open and I will test it sometimes, see if it works anytime soon, and finally close the issue. In the meantime, I will use the downloaded vsix file. Ok?

**Comment by hildjj** [comment]
That works for me.  Let's see what happens and then formulate a plan later in the week.

**Comment by medihack** [comment]
It seems Gitpod upgraded their VS Code and your extension now works in Gitpod correctly. Thanks a lot! Closing this issue now.

**Comment by hildjj** [comment]
I want to leave this open until I'm the verified owner of the PegJS namespace on VSX.
