### ISSUE TITLE
Is it possible to get syntax highlighting in template string?

### ISSUE THREAD

**Issue by sanket143** [peggyjs/code-peggy-language#21]
Like we have in GraphQL

https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql
![image](https://user-images.githubusercontent.com/26973649/166913389-eed418f8-cb6d-4e35-a7dd-6f853d224c37.png)

**Comment by hildjj** [comment]
Sorry I didn't get to this until now, I wanted to get Peggy2 out the door before thinking about it.

This is for people that don't pre-compile their grammars, and want to include `peggy` and `source-code-generate` as runtime dependencies, right?
