### ISSUE TITLE
"Goto/Peek Definition" doesn't work for proxy rules

### ISSUE THREAD

**Issue by nene** [peggyjs/code-peggy-language#29]
When trying to look up definition of a proxy rule, none is found:

![Screenshot 2022-11-18 at 15 12 20](https://user-images.githubusercontent.com/118201/202713160-a55dee8c-4a3c-4860-ae33-46dc75d299cf.png)

This likely happens because the rule gets optimized away:

![Screenshot 2022-11-18 at 15 13 21](https://user-images.githubusercontent.com/118201/202713341-c8b91893-314e-44e1-87f0-f8fed231ea2c.png)

I suppose one can simply refactor the proxy rule away, but I don't really want to do that. It's often helpful to have such proxy rules.

When one just turns off the "Peggy Language Server: Mark Info" config, the squiggly line won't appear under the rule, and it's even harder to diagnose why the lookup fails.

**Comment by nene** [comment]
I have a few ideas for solving this problem:

## The simplest just-delete-it solution

Simply remove the [removeProxyRules][] function from Peggy transform pass. As far as I understand, this transform exists purely for optimization purposes, as the editor plugin doesn't generate code, there's no actual need to perform that optimization.

The downside is that this eliminates the "Proxy rule 'foo' replaced by the rule 'bar'" info messages. I personally don't find these messages valuable. The blue squiggly line seems to suggest that there's something wrong with having a rule that's optimized away by the compiler. On the contrary I often find such rules useful for documentation purposes.

## The complex work-around-the-problem solution

Store all the proxy rule removal messages and use that info later when performing the "Goto/Peek definition" action to navigate to the.

This seems like a pretty bad approach as we would be keeping the source of the problem, and working around the issues caused by that.

## An intermediate make-it-harmless solution

Finally, we could replace the [removeProxyRules][] transform pass with one that only reports these info messages, but doesn't perform the actual transform. That way the info messages would still be there, but the transformations would not cause "Goto/Peek definition" to fail.

[removeProxyRules]: https://github.com/peggyjs/peggy/blob/main/lib/compiler/index.js#L53

**Comment by nene** [comment]
I tried out the simple solution, which is pretty much a single line of code:

```diff
 const PASSES: peggy.compiler.Stages = {
   check: peggy.compiler.passes.check,
-  transform: peggy.compiler.passes.transform,
+  transform: peggy.compiler.passes.transform.filter(fn => fn.name !== "removeProxyRules"),
   generate: [getWarnings],
 };
```

**Comment by hildjj** [comment]
I'm ok with just removing the compiler pass.

**Comment by hildjj** [comment]
When we fixed this, we removed the whole transform step.  We can't do without `inferenceMatchResult`, or the semantic pass will not work.  I'm going to add that back in #55.
