### ISSUE TITLE
Slow performance when working on a large grammar file

### ISSUE THREAD

**Issue by nene** [peggyjs/code-peggy-language#31]
I'm working with a large grammar file of about 4000 lines (see [parser.pegjs](https://github.com/nene/sql-parser-cst/blob/master/src/parser.pegjs)). At that size this extension becomes utterly sluggish.

It takes a few seconds to parse and compile the whole file, but the extension attempts to do that at every keystroke. So like when I type 10 characters I'll need to wait like 30 seconds for the extension to finish parsing and compiling the file 10 times in a row. When I write even longer passages of code, it can take several minutes for the extension to catch up.

I don't know what's the best practice for dealing with such long-executing processes in VSCode extension, but I guess something like wrapping the [validateTextDocument](https://github.com/peggyjs/code-peggy-language/blob/main/server/server.ts#L345) function call inside a [debounce](https://docs-lodash.com/v4/debounce/) would alleviate a large part of the pain.

**Comment by hildjj** [comment]
I'll at least add a debounce, and will think about other performance speedups while taking that pass.  I'm waiting for a Peggy release before picking this back up, so it might not be for several weeks, sorry.

**Comment by hildjj** [comment]
Not sure why this didn't get closed when #33 merged.  Closing now, but reopen if I missed something please.
