### ISSUE TITLE
Update to Peggy v3.0

### ISSUE THREAD

**Issue by horvathgyozo** [peggyjs/code-peggy-language#39]
Recently [peggy had an update to version 3](https://github.com/peggyjs/peggy/releases/tag/v3.0.0) with some new features, for which the actual vscode plugin shows errors.
Can you do a dependency update for the plugin?

**Comment by hildjj** [comment]
Working on it.  Will leave this open to track progress.

**Comment by hildjj** [comment]
Actually, I'd really like to wait for v3.0.1.  I'm looking at the last bug for that now.

**Comment by hildjj** [comment]
https://github.com/peggyjs/peggy/issues/357 if you'd like to help or watch progress.

**Comment by horvathgyozo** [comment]
Thank you!
