### ISSUE TITLE
Collaborate with vscode-pegjs

### ISSUE THREAD

**Issue by hildjj** [peggyjs/code-peggy-language#4]
See [repo](https://github.com/tamuratak/vscode-pegjs)

@tamuratak do you have any interest in collaborating?  We're re-invigorating Peg.js as Peggy, and in my opinion it would be great if we had one VSCode plugin that was a superset of the options the Peg.js world had.

**Comment by tamuratak** [comment]
I'm sorry, but I'm not interested at this time.

I do respect the development of Peggy. I hope it will be a success.
